document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("<title>舆情</title>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("* {");
document.writeln("    box-sizing: border-box;");
document.writeln("}");
document.writeln("body {");
document.writeln("    margin: 0;");
document.writeln("	background-color:#F0FFF0;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("footer {");
document.writeln("    border:1px;");
document.writeln("	background-color:#8B8386;");
document.writeln("	color:white;");
document.writeln("	text-align:center;");
document.writeln("	line-height:50px;");
document.writeln("	height:50px;");
document.writeln("	margin-top:300px;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("<footer>欢迎光临我的网站！</footer>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");