document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("<title>舆情</title>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("* {");
document.writeln("    box-sizing: border-box;");
document.writeln("}");
document.writeln("body {");
document.writeln("    margin: 0;");
document.writeln("	background-color:#F0FFF0;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("header {");
document.writeln("    border:1px solid;");
document.writeln("	height:100px;");
document.writeln("	background-color:#E0FFFF;");
document.writeln("	text-align:center;");
document.writeln("	font-size:2.5em;");
document.writeln("    padding-top:20px;");
document.writeln("");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<header>网络舆情分析</header>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");